### ISSUE TITLE
Deployment template missing workspace name

### ISSUE THREAD

**Issue by askvpb** [Bert-JanP/Sentinel-Automation#1]
Looks like there may be issues with the template missing the workspace name. 

![image](https://github.com/user-attachments/assets/c77f9a29-c5f5-4ae3-85de-e524d6a11164)

**Comment by Bert-JanP** [comment]
Thank you for raising the issue. 

It is in line 146:

`"path":"[concat('/Incidents/subscriptions/', subscription().subscriptionId, '/resourceGroups/', resourceGroup().name, '/workspaces/',parameters('WorkspaceName'))]"`

If you change the 

parameters('WorkspaceName') with 'yoursentinelworkspacename' it will be solved. I will investigate how to dynamically fix it.

**Comment by Bert-JanP** [comment]
New version is deployed. Additional parameter Sentinel Workspace Name is added which solves the issue.
![image](https://github.com/user-attachments/assets/85956ce4-14cf-4542-b279-92bc4784cb8c)
